Description: This module demonstrates a composition of resources, without an extension.

Parameters:
  AName:
    Type: String
  BName:
    Type: String

Resources:

  BucketA:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AName

  BucketB:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BName

