Transform: AWS::LanguageExtensions

Resources:

  Fn::ForEach::ForeachTestMakeHandles:
    - HandleName
    - - D
      - E
      - F
    - "ForeachTest${HandleName}":
        Type: AWS::CloudFormation::WaitConditionHandle
        Metadata: 
          Comment: !Sub "This is wait handle ${HandleName}"


