Resources:
  MyBucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: foo
      Parent:
        - Child:
            ShouldBeFalse: false
        - OtherChild: false
        - Subs:
          - "b0false"
          - "b1false"
  MyBucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bar
