Parameters:
  BucketRetentionPolicy:
    Type: String
    AllowedValues:
      - Delete
      - Retain
Conditions:
  ConditionA:
    !Equals:
      - true
      - true
Resources:
  MyBucket:
    Type: !Rain::Module "./test-module.yaml"
    Properties:
      LogBucketName: my-log-bucket
      RetentionPolicy: !Ref BucketRetentionPolicy
      ConditionName: ConditionA
    Overrides:
      Bucket:
        Condition: ConditionA
        DependsOn: SecondResourceInOriginal
        UpdateReplacePolicy: Delete
        Properties:
          BucketName: ezbeard-cep-test-module-bucket
          VersioningConfiguration:
            Status: Enabled
          Tags:
            - Key: test-tag2
              Value: test-value2
      LogBucket:
        Condition: ConditionA
  SecondResourceInOriginal:
    Type: AWS::SQS::Queue
  WithoutExtension:
    Type: !Rain::Module "./composite.yaml"
    Properties:
      AName: "AAA"
      BName: "BBB"

