Resources:
  MyLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        !Rain::S3
          Path: lambda-src
          Zip: true
          BucketProperty: S3Bucket
          KeyProperty: S3Key
      
