#!/bin/bash

set -eoux pipefail

go build ./cmd/rain

(
    staticcheck -f binary ./...
    staticcheck -tags=func_test -f binary ./...
) | staticcheck -merge

go vet ./...
go vet -tags=func_test ./...
go test ./...
go test -tags=func_test ./...
