- id: rain-format
  name: rain format
  description: Format AWS CloudFormation templates
  entry: rain
  language: golang
  files: \.(yml|yaml|json)$
  args: ["fmt", "-w"]

- id: rain-verify
  name: rain verify
  description: Verify AWS CloudFormation templates formatting without modifying files
  entry: rain
  language: golang
  files: \.(yml|yaml|json)$
  args: ["fmt", "-v"]
