Outputs:
  BucketName:
    Value:
      Fn::GetAtt:
      - ContentBucket
      - BucketName
Resources:
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: foo
  Foo:
    Type: A::B::C
    Properties:
      BucketName: !GetAtt ContentBucket.BucketName
