Parameters:
  ParentVal:
    Type: String
  pAppName:
    Type: String
Resources:
  MySubBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mod-in-mod-bucket
      XName:
        Fn::Sub: ${ParentVal}-abc
      YName:
        Fn::Sub: ${pAppName}-xyz
  MySubInDirBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mod-in-mod-bucket
      XName:
        Fn::Sub: ${ParentVal}-abc
      YName:
        Fn::Sub: ${pAppName}-xyz
  MySubInDirSubSubZ:
    Type: A::B::C
