package cmd_test

import (
	"os"

	"github.com/aws-cloudformation/rain/cmd"
)

func Example_build_bucket() {
	os.Args = []string{
		os.Args[0],
		"build",
		"AWS::S3::Bucket",
	}

	cmd.Execute(cmd.Rain)
	// Output:
	// AWSTemplateFormatVersion: "2010-09-09"
	//
	// Description: Template generated by cfn-skeleton
	//
	// Resources:
	//   MyBucket:
	//     Type: "AWS::S3::Bucket"
	//     Properties:
	//       AccelerateConfiguration:
	//         AccelerationStatus: CHANGEME
	//       AccessControl: CHANGEME  # Optional
	//       AnalyticsConfigurations:
	//         - Id: CHANGEME
	//           Prefix: CHANGEME  # Optional
	//           StorageClassAnalysis:
	//             DataExport:
	//               Destination:
	//                 BucketAccountId: CHANGEME
	//                 BucketArn: CHANGEME
	//                 Format: CHANGEME
	//                 Prefix: CHANGEME
	//               OutputSchemaVersion: CHANGEME
	//           TagFilters:  # Optional
	//             - Key: CHANGEME
	//               Value: CHANGEME
	//       BucketEncryption:
	//         ServerSideEncryptionConfiguration:
	//           - ServerSideEncryptionByDefault:
	//               KMSMasterKeyID: CHANGEME
	//               SSEAlgorithm: CHANGEME
	//       BucketName: CHANGEME  # Optional
	//       CorsConfiguration:
	//         CorsRules:
	//           - AllowedHeaders:
	//               - CHANGEME
	//             AllowedMethods:
	//               - CHANGEME
	//             AllowedOrigins:
	//               - CHANGEME
	//             ExposedHeaders:
	//               - CHANGEME
	//             Id: CHANGEME
	//             MaxAge: 0
	//       InventoryConfigurations:
	//         - Destination:
	//             BucketAccountId: CHANGEME
	//             BucketArn: CHANGEME
	//             Format: CHANGEME
	//             Prefix: CHANGEME
	//           Enabled: false
	//           Id: CHANGEME
	//           IncludedObjectVersions: CHANGEME
	//           OptionalFields:  # Optional
	//             - CHANGEME
	//           Prefix: CHANGEME  # Optional
	//           ScheduleFrequency: CHANGEME
	//       LifecycleConfiguration:
	//         Rules:
	//           - AbortIncompleteMultipartUpload:
	//               DaysAfterInitiation: 0
	//             ExpirationDate: "1970-01-01 00:00:00"
	//             ExpirationInDays: 0
	//             Id: CHANGEME
	//             NoncurrentVersionExpirationInDays: 0
	//             NoncurrentVersionTransition:
	//               StorageClass: CHANGEME
	//               TransitionInDays: 0
	//             NoncurrentVersionTransitions:
	//               - StorageClass: CHANGEME
	//                 TransitionInDays: 0
	//             Prefix: CHANGEME
	//             Status: CHANGEME
	//             TagFilters:
	//               - Key: CHANGEME
	//                 Value: CHANGEME
	//             Transition:
	//               StorageClass: CHANGEME
	//               TransitionDate: "1970-01-01 00:00:00"
	//               TransitionInDays: 0
	//             Transitions:
	//               - StorageClass: CHANGEME
	//                 TransitionDate: "1970-01-01 00:00:00"
	//                 TransitionInDays: 0
	//       LoggingConfiguration:
	//         DestinationBucketName: CHANGEME  # Optional
	//         LogFilePrefix: CHANGEME  # Optional
	//       MetricsConfigurations:
	//         - Id: CHANGEME
	//           Prefix: CHANGEME  # Optional
	//           TagFilters:  # Optional
	//             - Key: CHANGEME
	//               Value: CHANGEME
	//       NotificationConfiguration:
	//         LambdaConfigurations:  # Optional
	//           - Event: CHANGEME
	//             Filter:
	//               S3Key:
	//                 Rules:
	//                   - Name: CHANGEME
	//                     Value: CHANGEME
	//             Function: CHANGEME
	//         QueueConfigurations:  # Optional
	//           - Event: CHANGEME
	//             Filter:
	//               S3Key:
	//                 Rules:
	//                   - Name: CHANGEME
	//                     Value: CHANGEME
	//             Queue: CHANGEME
	//         TopicConfigurations:  # Optional
	//           - Event: CHANGEME
	//             Filter:
	//               S3Key:
	//                 Rules:
	//                   - Name: CHANGEME
	//                     Value: CHANGEME
	//             Topic: CHANGEME
	//       ObjectLockConfiguration:
	//         ObjectLockEnabled: CHANGEME  # Optional
	//         Rule:  # Optional
	//           DefaultRetention:
	//             Days: 0
	//             Mode: CHANGEME
	//             Years: 0
	//       ObjectLockEnabled: false  # Optional
	//       PublicAccessBlockConfiguration:
	//         BlockPublicAcls: false  # Optional
	//         BlockPublicPolicy: false  # Optional
	//         IgnorePublicAcls: false  # Optional
	//         RestrictPublicBuckets: false  # Optional
	//       ReplicationConfiguration:
	//         Role: CHANGEME
	//         Rules:
	//           - Destination:
	//               AccessControlTranslation:
	//                 Owner: CHANGEME
	//               Account: CHANGEME
	//               Bucket: CHANGEME
	//               EncryptionConfiguration:
	//                 ReplicaKmsKeyID: CHANGEME
	//               StorageClass: CHANGEME
	//             Id: CHANGEME
	//             Prefix: CHANGEME
	//             SourceSelectionCriteria:
	//               SseKmsEncryptedObjects:
	//                 Status: CHANGEME
	//             Status: CHANGEME
	//       Tags:
	//         - Key: CHANGEME
	//           Value: CHANGEME
	//       VersioningConfiguration:
	//         Status: CHANGEME
	//       WebsiteConfiguration:
	//         ErrorDocument: CHANGEME  # Optional
	//         IndexDocument: CHANGEME  # Optional
	//         RedirectAllRequestsTo:  # Optional
	//           HostName: CHANGEME
	//           Protocol: CHANGEME
	//         RoutingRules:  # Optional
	//           - RedirectRule:
	//               HostName: CHANGEME
	//               HttpRedirectCode: CHANGEME
	//               Protocol: CHANGEME
	//               ReplaceKeyPrefixWith: CHANGEME
	//               ReplaceKeyWith: CHANGEME
	//             RoutingRuleCondition:
	//               HttpErrorCodeReturnedEquals: CHANGEME
	//               KeyPrefixEquals: CHANGEME
	//
	// Outputs:
	//   MyBucketArn:
	//     Value: !GetAtt MyBucket.Arn
	//
	//   MyBucketDomainName:
	//     Value: !GetAtt MyBucket.DomainName
	//
	//   MyBucketDualStackDomainName:
	//     Value: !GetAtt MyBucket.DualStackDomainName
	//
	//   MyBucketRegionalDomainName:
	//     Value: !GetAtt MyBucket.RegionalDomainName
	//
	//   MyBucketWebsiteURL:
	//     Value: !GetAtt MyBucket.WebsiteURL
}
