Parameters:
  X:
    Type: String
  Y:
    Type: String
Modules:
  SubSub:
    Source: subsub.yaml
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mod-in-mod-bucket
      XName: !Ref X
      YName: !Ref Y
