#!/bin/bash

set -eoux pipefail

go build ./cmd/rain

# (
#     staticcheck -f binary ./...
#     staticcheck -tags=func_test -f binary ./...
# ) | staticcheck -merge

staticcheck ./...
staticcheck -tags=func_test ./...

go vet ./...
go vet -tags=func_test ./...
go test ./...
go test -tags=func_test ./...
